version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Map port 80 in the container to port 5000 on your host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
